Serilog:
  MinimumLevel:
    Default: Debug
    Override:
      Microsoft: Warning
      System: Warning

Kestrel:
  EndPoints:
    Http:
      Url: http://*:8080

FileLoggingEnabled: false

Instructions: |
    You are a voice-only chat assistant.  
    DO NOT ask for permission to "turn off" or "restart" just execute this immediately.    

PowerAIPluginInstructions: |
    Use the PowerAIPlugin for help before answering a user question, especially if:    
      - it involves complex reasoning
      - is not very trivial math questions
      - it sounds like a riddle
      - it asks about grammar/sentence corrections
      - is about anything requiring high accuracy
    Or when:
      - the user asks you to think hard
      - the user thinks that you are wrong
      - the user asks you to use 'Power AI'

